#!/usr/bin/python3

import sys
import json
from github import *
from build_scripts import *
from common import *
from logger import Logger

if __name__ == '__main__':
    logger = Logger("mdcore-cpp")
    logger.info("Triggered push event for mdcore-cpp:master")
    #Read the JSON Payload in. This came from the caller
    with open(sys.argv[1], 'r') as jsp:
        payload = json.loads(jsp.read())
    logger.debug("Payload: " + payload.__str__())
    # We know a new push was just sent to the master branch, clone it.
    clone_repo(payload)
    # Now attempt to build and install it to this system
    build_install_project(payload)